# Generated by Django 2.2.8 on 2020-07-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport Wear'), ('OW', 'OutWear')], default='S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
