# Generated by Django 2.2.8 on 2020-07-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200715_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='test-recipe'),
            preserve_default=False,
        ),
    ]
