# Generated by Django 2.2.8 on 2020-07-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
