# Generated by Django 2.2.8 on 2020-07-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='This is a test recipe: 1) eat some eggs, 2) eat more eggs, 3) eggs are good but these will probably be separate textfields stacked on top of one another'),
            preserve_default=False,
        ),
    ]
