# Generated by Django 2.2.8 on 2020-07-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecipe',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
