# Generated by Django 2.2.8 on 2020-07-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orderrecipe_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
