# Generated by Django 2.2.8 on 2020-07-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200718_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecipe',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='price',
            field=models.FloatField(),
        ),
    ]
