# Generated by Django 2.2.8 on 2020-07-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200718_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecipe',
            name='price',
            field=models.FloatField(),
        ),
    ]
