# Generated by Django 2.2.8 on 2020-07-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200718_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrecipe',
            name='price',
        ),
    ]
